apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: matveevali/medication-management
  newName: matveevali/medication-management # {"$imagepolicy":  "wac-hospital:medication-management:name"}
  newTag: main.20240420.1402 # {"$imagepolicy": "wac-hospital:medication-management:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: matveevali/ambulance-wl-webapi
  newName: matveevali/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240511.1438 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
