apiVersion: apps/v1
kind: Deployment
metadata:
  name: matveeva-ambulance-webapi
spec:
  template:
    spec:
      containers:
      - name: openapi-ui
        env:
        - name: URL
          value: /matveeva-openapi
        - name: BASE_URL
          value: /matveeva-openapi-ui