apiVersion: apps/v1
kind: Deployment
metadata:
  name: matveeva-medication-management-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /matveeva-openapi
            - name: BASE_URL
              value: /matveeva-openapi-ui
